/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTenant
 */
export interface PatchedTenant {
    /**
     * 
     * @type {string}
     * @memberof PatchedTenant
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTenant
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTenant
     */
    name?: string;
}

/**
 * Check if a given object implements the PatchedTenant interface.
 */
export function instanceOfPatchedTenant(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTenantFromJSON(json: any): PatchedTenant {
    return PatchedTenantFromJSONTyped(json, false);
}

export function PatchedTenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTenant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedTenantToJSON(value?: PatchedTenant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
    };
}

