/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionList
 */
export interface PermissionList {
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionList
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the PermissionList interface.
 */
export function instanceOfPermissionList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "permissions" in value;

    return isInstance;
}

export function PermissionListFromJSON(json: any): PermissionList {
    return PermissionListFromJSONTyped(json, false);
}

export function PermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permissions': json['permissions'],
    };
}

export function PermissionListToJSON(value?: PermissionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permissions': value.permissions,
    };
}

