/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleResponse
 */
export interface SimpleResponse {
    /**
     * 
     * @type {string}
     * @memberof SimpleResponse
     */
    message: string;
}

/**
 * Check if a given object implements the SimpleResponse interface.
 */
export function instanceOfSimpleResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function SimpleResponseFromJSON(json: any): SimpleResponse {
    return SimpleResponseFromJSONTyped(json, false);
}

export function SimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SimpleResponseToJSON(value?: SimpleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

