/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialAuthLogin
 */
export interface SocialAuthLogin {
    /**
     * 
     * @type {string}
     * @memberof SocialAuthLogin
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof SocialAuthLogin
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof SocialAuthLogin
     */
    idToken: string;
}

/**
 * Check if a given object implements the SocialAuthLogin interface.
 */
export function instanceOfSocialAuthLogin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "provider" in value;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "idToken" in value;

    return isInstance;
}

export function SocialAuthLoginFromJSON(json: any): SocialAuthLogin {
    return SocialAuthLoginFromJSONTyped(json, false);
}

export function SocialAuthLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialAuthLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'accessToken': json['access_token'],
        'idToken': json['id_token'],
    };
}

export function SocialAuthLoginToJSON(value?: SocialAuthLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
        'access_token': value.accessToken,
        'id_token': value.idToken,
    };
}

