/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformation
 */
export interface UserInformation {
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    readonly uuid: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UserInformation interface.
 */
export function instanceOfUserInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UserInformationFromJSON(json: any): UserInformation {
    return UserInformationFromJSONTyped(json, false);
}

export function UserInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'email': json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function UserInformationToJSON(value?: UserInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

