/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello Server API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPasswordLogin
 */
export interface UserPasswordLogin {
    /**
     * 
     * @type {string}
     * @memberof UserPasswordLogin
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserPasswordLogin
     */
    password: string;
}

/**
 * Check if a given object implements the UserPasswordLogin interface.
 */
export function instanceOfUserPasswordLogin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserPasswordLoginFromJSON(json: any): UserPasswordLogin {
    return UserPasswordLoginFromJSONTyped(json, false);
}

export function UserPasswordLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPasswordLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function UserPasswordLoginToJSON(value?: UserPasswordLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

